### ISSUE TITLE
How to cite section

### ISSUE THREAD

**Issue by mdesco** [scilus/tractoflow_documentation#7]
@GuillaumeTh should you add your biorxiv in the list and / or mention tractoflow-ABS?

**Comment by mdesco** [comment]
Je viens de voir le TIP plus bas. P-e bouger ton TIP dans la section how to cite aussi?

**Comment by GuillaumeTh** [comment]
Yes I will move the tip block in how to cite section too. And readd the biorxiv for TractoFlow-ABS

**Comment by GuillaumeTh** [comment]
Done
