### ISSUE TITLE
english errors

### ISSUE THREAD

**Issue by mdesco** [scilus/tractoflow_documentation#8]
- Two types of seeding is available: WM-GM interface or WM mask. > are available (Tractography part of the processing steps)

- TractoFlow support BIDS -> supports

- TractoFlow do some verifications before launching the procssing to validate BIDS format.
                     -> does    -> processing  -> to valide the BIDS format

-  is called using --root and require  -> requires

- P-e commencer cette phrase en disant, "It is possible not to follow the BIDS format. In that case, ... 

- fully_reproducible
Peux-tu esssayer de citer ton NeuroImage quand tu parles du profile fully_reproducible stp

- peut-etre rajouter une option tar cvzfh pour tar.gz le results et dire au monde qu'une tonne de log et fichiers symlink sont crees dans le work. le 'h' est important ici (je suis en train de tester... svp testez aussi)

- Good job! I will soon test the macosx and bids versions...

**Comment by GuillaumeTh** [comment]
Everything is corrected.
